"""Add LoginHistory model

Revision ID: 0574dc1c4e21
Revises: c63eee6e14b8
Create Date: 2026-02-09 13:59:42.005155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0574dc1c4e21'
down_revision = 'c63eee6e14b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_history_login_time'), ['login_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_history_login_time'))

    op.drop_table('login_history')
    # ### end Alembic commands ###
