"""Add indexes for search optimization

Revision ID: 630aa3a4c07c
Revises: c61f4cfda3ff
Create Date: 2026-02-09 11:22:51.524871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630aa3a4c07c'
down_revision = 'c61f4cfda3ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_title'), ['title'], unique=False)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_manager_id'), ['manager_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_position'), ['position'], unique=False)
        batch_op.drop_column('email')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_created_at'))
        batch_op.drop_index(batch_op.f('ix_feedback_category'))

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_index(batch_op.f('ix_employee_position'))
        batch_op.drop_index(batch_op.f('ix_employee_name'))
        batch_op.drop_index(batch_op.f('ix_employee_manager_id'))

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_title'))

    # ### end Alembic commands ###
