"""Add sales gamification models

Revision ID: d5f8c357d7ea
Revises: 0574dc1c4e21
Create Date: 2026-02-09 14:09:41.965849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f8c357d7ea'
down_revision = '0574dc1c4e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('condition_value', sa.Integer(), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['sales_task.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_progress_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_progress_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_progress_user_id'), ['user_id'], unique=False)

    op.create_table('user_achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['sales_achievement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievement_user_id'), ['user_id'], unique=False)

    op.create_table('user_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('achievements_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_points_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_points_user_id'))

    op.drop_table('user_points')
    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievement_user_id'))

    op.drop_table('user_achievement')
    with op.batch_alter_table('sales_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_sales_progress_task_id'))
        batch_op.drop_index(batch_op.f('ix_sales_progress_period_start'))

    op.drop_table('sales_progress')
    op.drop_table('sales_task')
    op.drop_table('sales_achievement')
    # ### end Alembic commands ###
